### ISSUE TITLE
Stop Listener when disposed

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-eventhubs-extension#104]
Creating an EventHubs-specific issue for this: https://github.com/Azure/azure-webjobs-sdk/issues/2823

After discussing internally with @alrod, we think that having the EH Listener also stop itself on the call to Dispose() (and skip checkpointing if disposed) is the safest path.

**Comment by alrod** [comment]
Looks like the same issue https://github.com/Azure/azure-functions-eventhubs-extension/issues/66

**Comment by liliankasem** [comment]
@alrod Did you want to use this issue to also track changes to the service bus listener or should we create a new issue in that repo?
