### ISSUE TITLE
Upgrade Event Hubs processor to 3.0

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-eventhubs-extension#13]
Some improvements and fixes with the latest version of the event processor host we should look at integrating into our trigger

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/3.0.0

We currently use `2.1.0`

A few other fixes we'll want to group in this:

- [ ]  Bump the version of Newtonsoft.Json
- [ ]  Allow a way for people to send to a specific partition (#1643)

**Comment by alrod** [comment]
The package uses EventHub processor 3.0:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/4.0.0-beta2

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-eventhubs-extension/commit/46db8a3f4bb09ef3b50a6088f8723a1a49a74d62
