### ISSUE TITLE
JSON deserializable string assumed without dataType

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-eventhubs-extension#17]
Repro steps:

1. Create a JavaScript EventHub triggered function from the default template
2. Write a plain string (e.g. "a") to the EventHub. Results in the following failure:
```
[9/3/2019 8:03:15 PM] System.Private.CoreLib: Exception while executing function: Functions.EventHubTrigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'eventHubMessages'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'Object
') uses Json.NET serialization.
1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: a. Path '', line 0, position 0.
```

Issue does not happen if we write a JSON (e.g. { "b" : "a" } to the EventHub or specify `dataType` as `string` in the `function.json`. 

Default behavior should be just to have the string without any deserialization?

**Comment by alrod** [comment]
This is expected behavior.
