### ISSUE TITLE
Functions V2 - EventHubTrigger - Unable to Start (conflicting reference on Microsoft.Azure.EventHubs)

### ISSUE THREAD

**Issue by willlaugesenst** [Azure/azure-functions-eventhubs-extension#34]
Hi,

I am facing the below error when trying to start my azure functions. The runtime for my azure functions is .netstandard 2.0.

My scenario is this: I have a common library(.netstandard) the functions has an EventHubTrigger and all was working well. 

After I add "Microsoft.Azure.Eventhubs" to the common library consumed by my function the error starts occurring. The reason I need this library is because the common library posts to EH directly (not using triggers)

Downgrading to version Microsoft.Azure.EventHubs 3.0.0 is a workaround and resolves the issue.

```
The listener for function 'xxx' was unable to start.
[13-Aug-19 16:27:51] The listener for function 'xxx' was unable to start. Microsoft.Azure.EventHubs.Processor: Encountered error while fetching the list of EventHub PartitionIds. Microsoft.Azure.EventHubs.Processor: Method not found: 'Microsoft.Azure.EventHubs.EventHubClient Microsoft.Azure.EventHubs.EventHubClient.Create(System.Uri, System.String, Microsoft.Azure.EventHubs.ITokenProvider, System.Nullable`1<System.TimeSpan>, Microsoft.Azure.EventHubs.TransportType)'.
```
This is because Microsoft.Azure.WebJobs.Extensions.EventHubs depends on version 3.0.0 of Microsoft.Azure.EventHubs, but other projects are using version 4.1.0. 

Causing the above conflict.

This is a request to update Microsoft.Azure.WebJobs.Extensions.EventHubs to use Version 4.1.0 of Microsoft.Azure.EventHubs

Thankyou

**Comment by alrod** [comment]
@willlaugesenst, which version of `Microsoft.Azure.WebJobs.Extensions.EventHubs` you are referencing?
Latest (https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/4.1.0) already uses Microsoft.Azure.EventHubs 4.1.0
