### ISSUE TITLE
Add logging for eventhub lifecycle events

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-eventhubs-extension#35]
We need better instrumentation of what is happening inside the event hubs extension (similar to the logging improvements recently made for blobs). What I'd like to see captured:
- The details when we begin to process events (i.e. inspect the PartitionContext on OpenAsync)
- The details when we stop processing events (PartitionContext on CloseAsync)
- When we physically write a checkpoint

**Comment by FinVamp1** [comment]
Related ask would be to be able to display the number of new Events waiting to be processed as the Scale Controller does.

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-eventhubs-extension/commit/7a1dc2bbef8541bcd7a580d6ce135e05ee1ef9ca
