### ISSUE TITLE
Send an event with partition key

### ISSUE THREAD

**Issue by EhsanAminii** [Azure/azure-functions-eventhubs-extension#36]
currently i have problem using IAsyncCollector<EventData> in order to send a message to Event hub with a partition key. how is possible to choose a partition key?

Sample Code: 
[EventHub("myevent", Connection = "connectionstring")] IAsyncCollector<EventData> outboundMessage)

is there any option to choose the partition key by using the following method?
await outboundMessage.AddAsync(message);

Thank you.
Ehsan

**Comment by alrod** [comment]
You can use [EventHub(TestHubName)] EventHubClient client as workaround for now

**Comment by alrod** [comment]
Closed as duplicate Azure/azure-sdk-for-net#28245
