### ISSUE TITLE
Add trigger execution details

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-eventhubs-extension#37]
ServiceBus trigger adds logs for trigger execution which are useful for CRIs investigations:
https://github.com/Azure/azure-functions-servicebus-extension/blob/4c4ef3252112bc822a5c80a26824b12146330650/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/ServiceBusTriggerInput.cs#L67

We need something similar for EventHub trigger.

**Comment by kulkarnisonia16** [comment]
Can you please add details to this issue?
