### ISSUE TITLE
Starting azure function fails on "Microsoft.Azure.EventHubs.Processor: Method not found"

### ISSUE THREAD

**Issue by amtayyem** [Azure/azure-functions-eventhubs-extension#44]
![image](https://user-images.githubusercontent.com/53434438/72901828-1dc07500-3d33-11ea-9543-b6c166a3953b.png)
 
Function version ~3 
Using Microsoft.Azure.WebJobs.Extensions.EventHubs version 4.1.0

The nuget has a dependency on Microsoft.Azure.EventHubs.Processor 3.0.0 and by default restores and loads 3.0.0

Workaround:
Referencing Microsoft.Azure.EventHubs.Processor 4.1.0 solved the issue

**Comment by alrod** [comment]
@amtayyem, can you please post your `.proj` file?

**Comment by kristerkarto** [comment]
Had the same issue with Microsoft.Azure.WebJobs.Extensions.EventHubs version 4.1.1
and installing latest Microsoft.Azure.EventHubs.Processor fixed the problem. 

This should be solved by package owner.

**Comment by skadiyam** [comment]
> Had the same issue with Microsoft.Azure.WebJobs.Extensions.EventHubs version 4.1.1
> and installing latest Microsoft.Azure.EventHubs.Processor fixed the problem.
> 
> This should be solved by package owner.

After adding Microsoft.Azure.EventHubs.Processor , I'm getting below error. Any thoughts?

`The listener for function 'EventHubTrigger' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'EventHubTrigger' was unable to start.
 ---> Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException: Encountered error while fetching the list of EventHub PartitionIds
 ---> System.ArgumentException: The parameter 'host' cannot be an empty string.
   at System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   at Microsoft.Azure.Amqp.Transport.TcpTransportInitiator.ConnectAsync(TimeSpan timeout, TransportAsyncCallbackArgs callbackArgs)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.ConnectAsync(TimeSpan timeout, TransportAsyncCallbackArgs callbackArgs)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsync(TimeSpan timeout, TransportAsyncCallbackArgs callbackArgs)`

**Comment by willvelida** [comment]
I also encountered this issue. Installing Microsoft.Azure.EventHubs.Processor 4.2.0 resolved it. For reference, here is my .csproj file

`
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.1.0" />
    <PackageReference Include="Bogus" Version="29.0.2" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.11.0" />
    <PackageReference Include="Microsoft.Azure.EventHubs" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.EventHubs.Processor" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
`

**Comment by kumarallamraju** [comment]
dotnet add package Microsoft.Azure.EventHubs.Processor --version 4.2.0 solved the issue. Thanks to @willvelida
