### ISSUE TITLE
Migrate to new client Azure.Messaging.EventHubs

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-eventhubs-extension#58]
https://github.com/Azure/azure-functions-eventhubs-extension

**Comment by DavidBurela** [comment]
What is this issue referring to?  It URL is linking back to this repo

**Comment by alrod** [comment]
[EventHub 5.0.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs) was released
