### ISSUE TITLE
Please Update Storage Dependencies

### ISSUE THREAD

**Issue by mattjohnsonpint** [Azure/azure-functions-eventhubs-extension#65]
Hi,

The [`Microsoft.Azure.WebJobs.Extensions.Storage`](https://github.com/Azure/azure-webjobs-sdk/releases/tag/storage-v4.0.0) package just got a major update to 4.0.0, which moves away from the old `Microsoft.WindowsAzure.Storage` APIs and now uses the latest `Microsoft.Azure.Storage` libraries.

Is there a similar update coming for `Microsoft.Azure.WebJobs.Extensions.EventHubs`?

I use both the extensions in the same project, and they are taking different downstream dependencies for the storage SDK.  It would be good to have them aligned.

Also, if I try to update the Storage extension anyway, I get an error at runtime:

```
[5/28/2020 11:25:15 PM] EventProcessorHost error (Action=Checking Leases, HostName=32b60314-146f-4ebe-be2d-113f1a7c6b05, PartitionId=1)
[5/28/2020 11:25:15 PM] Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time.
```

**Comment by mj1856** [comment]
Just to add, it looks like `Microsoft.Azure.WebJobs.Extensions.EventHubs` depends on `Microsoft.Azure.EventHubs.Processor` which is still using `WindowsAzure.Storage` in its latest release.

**Comment by mj1856** [comment]
Actually, it seems my error was caused by other issues.  Though it would still be good to upgrade the dependencies, they can indeed run side-by-side.

**Comment by PrzemekGawron** [comment]
Hi,

We are migrating our storage libraries from version 9.x.x to 11.x & 12.x and this package blocks us from complete removal of Microsoft.WindowsAzure.Storage 9.x.x dependency. Can this be upgraded please?

**Comment by maithilikotla** [comment]
Hi,
Getting this error when I upgrade function app with event hub trigger from netcore app 2.2 to 3.1 while upgrading the Microsoft.Azure.WebJobs.Extensions.EventHubs to 4.2.0

**Comment by PalakMahajanDA** [comment]
> Actually, it seems my error was caused by other issues. Though it would still be good to upgrade the dependencies, they can indeed run side-by-side.

Hey Can You please advise what was the issue We getting same issue

**Comment by shreyabatra4** [comment]
The 5.x extensions use Azure.storage.blobs 12.x libraries.
