### ISSUE TITLE
Optimize the extension to prevent partition rebalancing from occurring.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-eventhubs-extension#67]
As per the documentation on storage [partitioning](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#partitioning), The partition server where a blob would be processed is determined by the partition key generated for the blob. 

> Each blob has a partition key comprised of the full blob name (account+container+blob). The partition key is used to partition blob data into ranges. The ranges are then load-balanced across Blob storage. Range-based partitioning means that naming conventions that use lexical ordering (for example, mypayroll, myperformance, myemployees, etc.) or timestamps (log20160101, log20160102, log20160102, etc.) are more likely to result in the partitions being co-located on the same partition server.”

The container name for the event hub and function host start with the same prefix. So it is possible that all the blob operations are happening on the same partition server, increasing the chance of partition rebalancing operation.

**Comment by dtangren2** [comment]
This is an important fix for us.  This particular issue has impacted production reliability for an architecture we have that relies on EventHub.  We raised a ticket with Microsoft support, and found through review and trial/error that this patch is our only viable solution, other than a potential replatforming away from EventHub.  Hoping this change can be added to a release quickly.

**Comment by cachai2** [comment]
@soninaren can you elaborate on the exact ask? We've improved checkpointing for the Event Hubs extension in version 5.0+. Can you please try this and see if it improves upon the required scenarios?

**Comment by alrod** [comment]
Close as no enough info.
