### ISSUE TITLE
After recent Azure update new functions deployments stop getting new events from Event Hub

### ISSUE THREAD

**Issue by markcandelora** [Azure/azure-functions-eventhubs-extension#68]
A recent Azure update (around 6/9) causes the function to stop executing on new event hub messages.  We're currently on version 4.1.1, and we've found that deleting either the consumer group or the checkpoint files in Blob Storage cause the function to start processing everything stored in the event hub (as one might expect).

We've been using v4.1.1 for months before this happened, so our assumption is that some update to the Azure Functions Host or Azure Storage Accounts is causing this. 

We found that downgrading from 4.1.1 to 3.0.6 fixes the issue.

Below is our project file with packages:
```XML
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.1.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.1" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
```

To fix this we simply downgraded the project to version 3.0.6:
```XML
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.1.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="3.0.6" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
```

**Comment by markcandelora** [comment]
Is there any update on this? This issue has regressed in our clients' production environment.  It appears the 3.0.6 package is no longer functioning.

**Comment by scuderig** [comment]
Is there any update on this issue?

I have suspicion we have the same issue (we have not tried to downgrade to 3.0.6 based on the last comment)

**Comment by markcandelora** [comment]
It looks like the Microsoft team isn't active at all.  It's a little frustrating since this is supposed to be their new mode of operation, but maybe not all teams are on board with that :-/

Echo! (Echo echo echo echo)  Yep, no one's here.

**Comment by alrod** [comment]
@[markcandelora](https://github.com/markcandelora), do you still experiencing the issue?
do you have the same issue with EventHub extension 5.0.0? 4.1.1 and 3.0.6 are pretty old versions.

**Comment by markcandelora** [comment]
Hi, we've moved on from this solution that was having the problem.  We haven't run into this problem since last year.

**Comment by alrod** [comment]
closing as old issue.
