### ISSUE TITLE
Maximum event message size should be 1MB

### ISSUE THREAD

**Issue by sebader** [Azure/azure-functions-eventhubs-extension#8]
I believe the maximum event message size is wrong in the binding. It was probably not updated when Event Hub upgraded to 1MB limit of messages: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas

This should be 1 MB (or close to it, depending on how much space you want to leave for headers)

https://github.com/Azure/azure-functions-eventhubs-extension/blob/daed50dcc37da216869db1366a0a1d73d5a11a4f/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Triggers/EventHubAsyncCollector.cs#L27

**Comment by alrod** [comment]
After testing in production it turned out different tiers have different max message sizes.
standard: 1MB
basic: 256KB

We need to stick with 256KB for now. Also there is no way to get pricing tier for an Event Hub using SDK.

**Comment by sebader** [comment]
@alrod erally? Where did you see this? I can't find any different limits apart from the 1MB. 

Would it maybe at least be possible to make the 256KB the default in the binding but allow in overwrite via the host.json config?!

**Comment by alrod** [comment]
I tested this using console app and latest eventhub sdk (4.1.0) sending messages of different sizes.

Overwriting in host.json sounds as good idea, I created an issue to track. As workaround you can bind to `[EventHub(TestHubName)] EventHubClient client` in azure function and send a message more than 256KB using EventHubClient.

**Comment by sebader** [comment]
Yeah I just tested myself and you are right, Basic event hub has still the limit of 256KB message size. Doesn't seem to be documented anywhere. I'll reach out to the PG.

**Comment by nzthiago** [comment]
@alrod - that workaround would only work for .NET Functions right? For other functions we'd have to wait until the linked issue you created is fixed?

**Comment by Josh-Broughton** [comment]
@nzthiago This should work for any functions that have an azure event hub sdk. You should be able to find the correct sdk for your language here https://docs.microsoft.com/en-us/azure/event-hubs/sdks

**Comment by nzthiago** [comment]
> @nzthiago This should work for any functions that have an azure event hub sdk. You should be able to find the correct sdk for your language here https://docs.microsoft.com/en-us/azure/event-hubs/sdks

Sure if you want to forego Functions bindings altogether you can just use the SDK for any of the languages in your own functions code, that is the workaround our customers are using. But if using bindings, .NET is the only one that lets you bind to EventHubClient.
