### ISSUE TITLE
IoT Hub output binding as Event Hub doesn't work

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-eventhubs-extension#80]
I tried IoT Hub output binding from Node.js function as following documentation.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-iot-output?tabs=javascript

But following error shows and the function is failed.
> Unauthorized access. 'Send' claim(s) are required to perform this operation

![image](https://user-images.githubusercontent.com/4566555/97923410-49cc5480-1da1-11eb-992f-35c691dd0fef.png)

It seems that a connection string, which starts with `Endpoint=sb:// ... ` and was set when adding the binding from portal, doesn't have enough permission.

Is this binding supported currently? # [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp#supported-bindings) says this is supported.
If this is supported, could you please let me know how to get appropriate connection string?

\# As long as I know, EventHubs extention is used for IoT Hub binding, so I filed to this repo. Please let me know if this is wrong.

**Comment by horihiro** [comment]
According to following documetation of IoT Hub, it seems that the built-in Event Hub endpoint in IoT Hub is for only event reading, not writing.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin#read-from-the-built-in-endpoint

So if the output binding uses the built-in endpoint, I suspect the binding cannot write event.

**Comment by horihiro** [comment]
Hello @soninaren , could you please look into this?

**Comment by phooey** [comment]
> Hello @soninaren , could you please look into this?

I'm interested too, I have confirmed the same issue.

**Comment by hromanko** [comment]
Yes this would be the expected behaviour on attempting to publish to an IotHub EventHub endpoint as they are read only.  I'm not sure if there is an connection string or identity that would solve the issue OR if the documentation is incorrect.

**Comment by soninaren** [comment]
The IotHub template is actually an alias for eventHub Trigger. The function expected eventhub connection string with manage permissions. The messages are read from eventhub directly. Functions runtime does not connect to the IotHub directly.
