### ISSUE TITLE
Event Hub Extension Feature Request: Log the details about the Event Hub being monitored in the Bindings and also the Storage account.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-eventhubs-extension#89]
**Repro steps**
Customers use the Event Hub Extensions bindings very frequently.
If these don't work then we need to ask the customer for the details of those Event Hubs and the related Storage account to see if there is an issue on that side.

Adding this information when the Event Hub extension starts to listen on the Event Hub extensions would allow us to be able to
a) Build Detectors that access this information if the customer does raise a support request.
b) Look at automated solutions that will check connectivity to the EventHub namespace and allow the customer to resolve transient issues on their own.

**Expected behavior**
A log entry is written when we attach to the binding.

**Actual behavior**
We log information about the Event Hub and Partition Count but not the FQDN of the Event Hub Namespace.

**Known workarounds**
No workarounds exist.

**Comment by alrod** [comment]
This was already done for track2, need a port to track1
