### ISSUE TITLE
Include the Function name on log messages

### ISSUE THREAD

**Issue by sidkri** [Azure/azure-functions-eventhubs-extension#94]
Having the function name (Azure Functions function, not c# function) on log messages is useful when the event/exception occurred in the context of invoking a specific function.  Similar to the [work done for the Service Bus extension](https://github.com/Azure/azure-functions-servicebus-extension/pull/163) the Event Hubs extension should do the same.  This will also be needed by the upcoming detector (@madelinegordon FYI).

**Comment by alrod** [comment]
Done.
